### PR TITLE
Updated lf to version 3.2.1.

### PR DESCRIPTION
**Pull request by gellweiler**
Updated LF to version 3.2.1 switched to the new moonlight server.

### CODE REVIEW

**Comment by pangelo** [comment]
Hello. Thanks for updating this and contributing it back :)

The patch looks good, I'll test it during this week and merge it if I don't find any issues with it.

**Comment by crack00r** [comment]
any updates on this?

**Comment by christian-weiss** [comment]
I tried to verify your pull request.

Output of: 
`docker build -t liquid-feedback . `
looks ok. 

But: 
`docker run liquid-feedback`
runs endless, and output is:
```
$ docker run liquid-feedback
Starting PostgreSQL 9.4 database server: main.
2017-10-01 15:24:48 UTC: Starting moonbridge server
2017-10-01 15:24:48 UTC: Loading "/opt/lf/webmcp/bin/mcp.lua"
2017-10-01 15:24:48 UTC: Creating pool
2017-10-01 15:24:48 UTC: Adding TCP listener on interface "0.0.0.0", port 8080
2017-10-01 15:24:48 UTC: Pool #1 created
2017-10-01 15:24:48 UTC: Creating pool
2017-10-01 15:24:48 UTC: Adding interval listener "send_pending_notifications"
2017-10-01 15:24:48 UTC: Pool #2 created
```

And WebUI at http://localhost:8080/ is not available.

@gellweiler Would be very nice if you can update your pull request.
BTW: Liquid Feedback Core 4.0 was released some days ago. So you may want to update to 4.0. 

UPDATE:
Looks like output of
`docker build -t liquid-feedback . `
is not ok. 

```
INSERT 0 1
[91mpsql:/opt/lf/sources/scripts/config_db.sql:15: ERROR:  column "admission_time" of relation "policy" does not exist
LINE 1: INSERT INTO policy (index, name, admission_time, discussion_...
                                         ^
[0mINSERT 0 1
INSERT 0 1
[91mpsql:/opt/lf/sources/scripts/config_db.sql:21: ERROR:  insert or update on table "allowed_policy" violates foreign key constraint "allowed_policy_policy_id_fkey"
DETAIL:  Key (policy_id)=(1) is not present in table "policy".
[0mINSERT 0 1
```

**Comment by pangelo** [comment]
Sorry this took so long to merge. I'm currently updating the Dockerfile to a new version and wanted to credit you for all the hard work you put into this patch. 

Thank you.

**Pull request merged**
